
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 04 19:28:09 VET 2012
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int MOD = 18;
  public static final int AND = 24;
  public static final int CADENA = 9;
  public static final int OR = 25;
  public static final int IGUAL = 11;
  public static final int FINPROGRAM = 4;
  public static final int RPARENT = 21;
  public static final int SUMA = 14;
  public static final int SIGNO = 19;
  public static final int DIVI = 17;
  public static final int WRITELN = 13;
  public static final int NOT = 26;
  public static final int END = 30;
  public static final int LINEANUEVA = 31;
  public static final int RCORCHE = 23;
  public static final int DOSP = 29;
  public static final int WRITE = 12;
  public static final int PROGRAM = 2;
  public static final int BEGIN = 3;
  public static final int BOOLEAN = 7;
  public static final int PTCO = 28;
  public static final int COMA = 27;
  public static final int LPARENT = 20;
  public static final int EOF = 0;
  public static final int MULT = 16;
  public static final int LCORCHE = 22;
  public static final int error = 1;
  public static final int NUMERO = 10;
  public static final int IDENTIFICADOR = 8;
  public static final int INTEGER = 6;
  public static final int REST = 15;
  public static final int VAR = 5;
}

