
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 03 19:05:47 VET 2012
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int MOD = 14;
  public static final int AND = 20;
  public static final int CADENA = 7;
  public static final int OR = 21;
  public static final int IGUAL = 9;
  public static final int FINPROGRAM = 4;
  public static final int RPARENT = 17;
  public static final int SUMA = 10;
  public static final int SIGNO = 15;
  public static final int WRITELN = 6;
  public static final int DIVI = 13;
  public static final int NOT = 22;
  public static final int END = 25;
  public static final int LINEANUEVA = 26;
  public static final int RCORCHE = 19;
  public static final int WRITE = 5;
  public static final int PROGRAM = 2;
  public static final int BEGIN = 3;
  public static final int PTCO = 24;
  public static final int COMA = 23;
  public static final int LPARENT = 16;
  public static final int EOF = 0;
  public static final int MULT = 12;
  public static final int LCORCHE = 18;
  public static final int error = 1;
  public static final int NUMERO = 8;
  public static final int IDENTIFICADOR = 27;
  public static final int REST = 11;
}

