
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Nov 03 17:43:10 VET 2012
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int CADENA = 9;
  public static final int RPARENT = 8;
  public static final int PROGRAM = 2;
  public static final int FINPROGRAM = 4;
  public static final int WRITELN = 6;
  public static final int LINEANUEVA = 12;
  public static final int EOF = 0;
  public static final int NUMERO = 14;
  public static final int PTCO = 10;
  public static final int WRITE = 5;
  public static final int error = 1;
  public static final int END = 11;
  public static final int LPARENT = 7;
  public static final int BEGIN = 3;
  public static final int IDENTIFICADOR = 13;
}

